### ISSUE TITLE
Simplify give_is_admin_page conditional

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1091]
## Issue Overview

The `give_is_admin_page` conditional is a giant conditional mess: https://github.com/WordImpress/Give/blob/master/includes/admin/admin-pages.php#L71

It's hard to read and lowers our code quality + scrutinizer score. Let's fix it. 
## Possible Solution

Use `get_current_screen` function and check against a simplified set of conditions.
## Todos
- [ ] Determine whether this function is necessary, it appears only to be in use to conditionally load admin scripts. I only found one other usage within the Recurring add-on. 
- [ ] Figure method to simplify function
- [ ] Develop chosen method
- [ ] Test chosen method

**Comment by ramiy** [comment]
I've found only two add-ons that use the `give-manual-donations` function/hook:

* Give Manual Donations
* Give Recurring Donations

We need to update them too.

**Comment by ramiy** [comment]
By the way, we don't have to simplify the function, we can replace/rewrite the code the uses this function. And then to deprecate this dinosaur.
