### ISSUE TITLE
Handle give_field_is_required() differently

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1212]
## Issue Overview
Our current implementation of give_field_is_required() requires that we do conditional checks within the markup of the template file itself. I believe we should be able to have a more elegant function which runs on its own per field and only adds the class "required" to a field if the function returns true for that field.

## Current Behavior
Here's the markup for the current "First Name" field:

```
<p id="give-first-name-wrap" class="form-row form-row-first">
	<label class="give-label" for="give-first">
		<?php esc_html_e( 'First Name', 'give' ); ?>
		<?php if ( give_field_is_required( 'give_first', $form_id ) ) { ?>
			<span class="give-required-indicator">*</span>
		<?php } ?>
		<span class="give-tooltip give-icon give-icon-question" data-tooltip="<?php esc_html_e( 'We will use this to personalize your account experience.', 'give' ); ?>"></span>
	</label>
	<input class="give-input required" type="text" name="give_first" placeholder="<?php esc_html_e( 'First Name', 'give' ); ?>" id="give-first" value="<?php echo is_user_logged_in() ? $user_data->first_name : ''; ?>"<?php if ( give_field_is_required( 'give_first', $form_id ) ) {
		echo ' required ';
	} ?>/>
</p>
```

It's functional, but a bit messy to read particularly for theme authors.

## Possible Solution
Instead, let's clean it up with a more powerful and elegant required field function, like so:

```
<p id="give-first-name-wrap" class="form-row form-row-first">
	<label class="give-label <?php give_field_is_required( 'give_first', $form_id ) ); ?>" for="give-first">
		<?php esc_html_e( 'First Name', 'give' ); ?>
		<span class="give-tooltip give-icon give-icon-question" data-tooltip="<?php esc_html_e( 'We will use this to personalize your account experience.', 'give' ); ?>"></span>
	</label>
	<input class="give-input required" type="text" name="give_first" placeholder="<?php esc_html_e( 'First Name', 'give' ); ?>" id="give-first" value="<?php echo is_user_logged_in() ? $user_data->first_name : ''; ?>"<?php give_field_is_required( 'give_first', $form_id ) ); ?> />
</p>
```

So the whole job of this function is simply to return the word "required" if required. Above, there are two examples, here's how/why they work:

1. The first is placed in the class of the label. Instead of outputting a span with an aeterisk, we simply return the class name, and the aesterisk is output with CSS like so:
```
.give-label.required:after {
    content: '*';
    color: red;
    display: inline;
}
```
2. The second instance is in the <input> field. Just like the first instance, it only needs to return the word "required" in order to work correctly.

You'll notice that I'm still passing the field name and the form id, those of course are needed to check whether this particular form is requiring those fields or not, just like it does currently. The only difference is that the sum result is that the only purpose of this whole function is simply to check whether the field is required or not, and return "required" or nothing at all.

## Related PRs
This most likely should be done together with the Form API overhaul here: https://github.com/WordImpress/Give/issues/1038

## Todos
- [ ] Create the function
- [ ] Test that it works with default forms and settings
- [ ] Test that it works with existing snippets and hooks which alter required fields
- [ ] Test that it works with Form Field Manager and any other Add-ons that affect front-end fields

**Comment by ravinderk** [comment]
@mathetos @Devinwalker I considered this issue while developing Form API for Give core. Currently, form API is still in development but you can check some WIP links:

https://github.com/WordImpress/Give/blob/issues/1038/includes/forms/api/class-give-fields-api.php#L33
https://github.com/WordImpress/Give/blob/issues/1038/includes/forms/api/class-give-fields-api.php#L1187
https://github.com/WordImpress/Give/blob/issues/1038/includes/forms/api/class-give-fields-api.php#L506

I will revisit this when I will start working on Form API

**Comment by DevinWalker** [comment]
Closing in favor of form API
