### ISSUE TITLE
Allow for currencies to be set per-form programatically

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1307]
## Issue Overview

Currently `give_get_currency` is not passed a `form_id`. This makes manipulating the currency per form very difficult via code. It's a semi-common request to be able to customize the currency per form. See: https://wordpress.org/support/topic/multi-currency-and-multi-language/

We should make it easier for users via a snippet: https://github.com/WordImpress/Give-Snippet-Library

This will also lay the groundwork for an official Add-on.

## Possible Solution
Pass the `$form_id` through `give_get_currency` and the `give_currency` filter. As well, we should pass the it through `give_get_currency_position` so the currencies positioning can be set as well. 

## Considerations
1. Formatting of currencies per form 
2. Currency symbol positioning 
3. Currency symbol with AJAX switching gateways
4. Currency symbol on donation receipt page
5. Currency display within donations screen

## Todos
- [ ] Code the ability to set per form ID the currency
- [ ] Verify formatting / symbol per the considerations above
- [ ] Create a snippet for the library
- [ ] Submit PR, Test, Merge

**Comment by ravinderk** [comment]
@DevinWalker This function has been updated in `2.0`. Let me know what do you think?
And we also changed currency registration API too. We can publish an article on developer blog posts to guide developer.

For ref: https://github.com/WordImpress/Give/blob/4257eaa97708b5db367ec382a3efd31894e10808/includes/currency-functions.php#L23

**Comment by DevinWalker** [comment]
Yeah I think it just needs a developers post and then we can close this one out.

**Comment by mathetos** [comment]
@DevinWalker I think this shouldn't be on the Dev blog, but perhaps as a Snippet instead. We don't use the Developer blog (currently) for resources at all, and this would be a live code example, or documentation.

**Comment by DevinWalker** [comment]
I'm fine with that @mathetos sure. I'll put together a snippet now.

**Comment by DevinWalker** [comment]
Working snippet is here: https://github.com/WordImpress/Give-Snippet-Library/blob/master/form-customizations/custom-per-form-currency.php

**Comment by DevinWalker** [comment]
Closing in favor of https://github.com/WordImpress/Give-Currency-Switcher/issues/114
