### ISSUE TITLE
feat(modal): create modal API to replace JS alerts

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#1475]
## Issue Overview

I think we can utilize magnific popup js to create modals on frontend and backend both instead of default alert messages.
https://github.com/WordImpress/Give/blob/master/assets/js/plugins/jquery.magnific-popup.js

## Todos
- [x] Implement `prototype-based` API for Magnific Popup
- [x] Allow developers to chain methods to configure popup
- [x] Implement JS filter hooks to extend the capability of the API
- [x] Add 5 types of popup: Default, Success, Notice, Warning, Error
- [x] Enable developers to add custom buttons
- [x] Style the popup as close to WordPress' UI/UX
---
- [x] Rewrite the above API using ES6 classes
- [x] Implement [ITCSS methodology](https://www.xfive.co/blog/itcss-scalable-maintainable-css-architecture/) and [CSS Guidelines](https://cssguidelin.es/) for CSS after discussion with 
- [x] Integrate Modal API in core
- [x] Replace alert and confirm with Modal API
@kevinwhoffman

**Comment by kevinwhoffman** [comment]
@Sidsector9 @ravinderk Please update the task list with remaining tasks.

**Comment by Sidsector9** [comment]
The task list has been updated.

CC: @ravinderk @kevinwhoffman
