### ISSUE TITLE
Settings API: New API Key Field Needed 

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1540]
## Issue Overview
Give payment gateways require a field that is first a text field when not completed with customizable placeholder text. When the field has a value saved, it is turned into a password field. 

This has been brought up by our customers a number of times and the most common scenario is that they don't want sensitive information freely viewable by other site admins. As well, we can suggest Lockr if they want super secure protection once that integration is released.

## Todos
- [ ] Develop new Settings API field
- [ ] Test with individual plugins
- [ ] Integrate with each payment gateway
