### ISSUE TITLE
Donor, Donation, and Donation Form Dropdowns need to be AJAX powered

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1572]
## Issue Overview

We have several places in which we list donors, or donations, or donation forms via a select field (or Select2). We're currently limiting the results to the most recent 30 results:

Forms = https://github.com/WordImpress/Give/blob/master/includes/class-give-html-elements.php#L110

Donors = https://github.com/WordImpress/Give/blob/master/includes/class-give-html-elements.php#L175

Donations = https://github.com/WordImpress/Give/blob/master/includes/class-give-html-elements.php#L47

Anytime a site has more than 30 donors, donations, or forms the select field results are then automatically incomplete, making those settings mute. 

## Expected Behavior
Site Admins should be able to search dynamically in those select fields for any matching donor, donation, or form.

## Current Behavior
They are currently limited to 30 results and there is no filter.

## Possible Solution
This post points in the right direction:
http://wordpress.stackexchange.com/questions/174261/wordpress-dynamic-ajax-query

## Related PRs
We addressed this issue in Manual Donations by making the results infinite -- not a scalable solution:
https://github.com/WordImpress/Give-Manual-Donations/issues/33

## Todos
- [x] Setup an environment that has at least 100 donors, donations, and/or forms for full testing
- [x] Test to ensure that you can find all donors, donations, and/or forms by searching
- [x] Ensure that the searched-for values are saved correctly after being chosen

**Comment by Benunc** [comment]
Had a support request for this today. Specifically the donor dropdown.

**Comment by DevinWalker** [comment]
We're bumping this to version 2.0 for inclusion within the Form API. This will allow us to use it on the frontend and backend.

**Comment by mathetos** [comment]
Here's a Give user reporting this, as well as my current "hack" to get around it:
https://wordpress.org/support/topic/more-than-30-forms/

**Comment by DevinWalker** [comment]
@ravinderk I'm going to need your JS wizardry on this one to smooth this out. I have it working but it's pretty buggy. The issue is similar to as described by this repo: https://github.com/meltingice/ajax-chosen

> If the user types a few letters, pauses, ajax fires off and returns results. Then the user types more, the chosen plugin will filter the results via JS as well as the server from the ajax call.

It makes for a lackluster user experience. I checked out EDD's code as well, and to be honest, it doesn't work very well either. 

I then researched this repo: https://github.com/meltingice/ajax-chosen and noticed within the code here: https://github.com/ksykulev/chosen-ajax-addition/blob/master/chosen.ajaxaddition.jquery.js#L58 where it appears the code is discarding old requests when new typing occurs. The demo they provide is pretty smooth when you type state names: http://sykulev.com/ajaxchosen/

Can we do a call about this after you get online and review?
