### ISSUE TITLE
Support Posting data to Give via the Give API

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1576]
## Issue Overview

Our Give API is currently read only. Would be useful for users to be able to use POST functions as well.

## Todos
- [ ] Implement POST feature
- [ ] Test for possible security concerns
- [ ] Create a sample function to run POST tests against

**Comment by DevinWalker** [comment]
With posting you have to worry about authentication which can lead to heavy development due to all the security concerns. I'm not so sure we want to take on this burden when the WP-API is going to be doing this for us. Rather, I'd like to see how we can use the WP API to handle this.

**Comment by mathetos** [comment]
I like that idea. Maybe we could work with the existing WP-API plugin and see if we can do a tutorial on leveraging that with Give? That would be a great tutorial for our readers/users.

**Comment by DevinWalker** [comment]
Yeah that sounds good. I believe it will work without the WP-API plugin but I haven't dug into it. Closing this one out
