### ISSUE TITLE
Exports should relocate to Donations > Tools > Exports

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1702]
## Issue Overview
It doesn't make sense to have exports under reports. It's confusing and it's really a tool rather than a report. See for instance with recurring and fee recovery enabled how it's even more odd in placement:

![2017-05-17_15-50-13](https://cloud.githubusercontent.com/assets/1571635/26179430/85685f9e-3b18-11e7-8e5e-d3dd64548fea.png)

## Todos
- [ ] Move and refactor file location
- [ ] Test exports to ensure compatiblity
- [ ] Update documentation - @mathetos can you help with this?

**Comment by mathetos** [comment]
@DevinWalker I created this issue in Give-Docs to address that once 1.8.8 is released:
https://github.com/WordImpress/Give-Docs/issues/81
