### ISSUE TITLE
Refactor log

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#1796]
## Issue Overview

From the performance perspective, it is good to store logs into their own table.

## Todos
- [x] Create table to store logs
- [x] Create table to store log meta
- [x] Refactor log code to use new database tables
- [x] Add backward compatibility
- [ ] Add PHPUnit tests
