### ISSUE TITLE
Including ESLint for JS coding standards

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#1827]
## Issue Overview
We've noticed that JS formatting issue comes up whenever JS config is different on different systems. So @DevinWalker @ravinderk and myself, had a discussion over slack for having a common config file for JS coding standards of WordPress.

## Expected Behavior
Using JS coding standards of WordPress.

## Current Behavior
JS formatting issues 

## Possible Solution
We've decided to include `JS config file of ESLint` in Give Core to follow common JS coding standards for everyone.

http://eslint.org/
https://github.com/WordPress-Coding-Standards/eslint-config-wordpress

## Todos
- [x] Create a config file
- [x] Configure it with PHPStorm
- [x] Update `.CONTRIBUTING` with instructions on using the standard.
- [x] Test to ensure setup is working properly. 
- [x] Add post on developers.givewp.com to help inform developers on the upcoming change
