### ISSUE TITLE
Minimum and maximum donation amount slider

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1920]
## Issue Overview
Most gateways have a maximum amount allowed to give online. 

- PayPal is $10,000: https://www.paypal.com/us/selfhelp/article/What-is-the-maximum-amount-I-can-send-with-my-PayPal-account-FAQ732
- Stripe is $999,999.99 https://support.stripe.com/questions/what-is-the-maximum-amount-i-can-charge-with-stripe

As well, many organizations and campaigns set the limit to $5,000 per donation. 

**Note:** We do have a snippet to limit maximum amount here - https://github.com/WordImpress/Give-Snippet-Library/blob/master/admin-functions/maximum-donation-amount.php

We should change the "Minimum Amount" option to be a range slider:

![2017-07-26_13-45-56](https://user-images.githubusercontent.com/1571635/28642913-df8ec5ae-7208-11e7-9fd3-bdda9fe35770.png) 

- Minimum amount is $1
- Maximum amount is $999,999.99

## Todos
- [x] Create new range slider field
- [ ] Add backwards compatibility to support current minimum amount option 
- [x] Code maximum amount logic
- [x] Tests

**Comment by emgk** [comment]
@DevinWalker when having large maximum amount suppose $999999.99. 
In that case, it will be hard to set any decided value _(for eg. less than 100)_ because due to the small width and high maximum value of the range slider it's stepping out the value based on the maximum range value.

See screenshot below: 


![ezgif-4-4e5b0d5863](https://user-images.githubusercontent.com/14994452/34521361-5f096270-f0b3-11e7-9d95-f9795e05f4aa.gif)


#### Possible Solution 
Let admin decide the maximum amount for **Minimum Amount** range slider field. For that, we can add a new field in the global setting which will allow the admin to set the maximum amount for **Minimum Amount** range slider field.

**Comment by DevinWalker** [comment]
@emgk I see what you mean. How about this: Can we make the minimum and maximum amount actual fields that the admin can click in and adjust if the filter slider isn't allowing the fine tuned range? That's just one idea I had to get around this limitation.

**Comment by emgk** [comment]
@DevinWalker So there would be both options _( using field or range slider )_ for admin to set the min and max amount. Also, min and max input field's value will be change based on range slider.

Please confirm layout below and let me know your thought: 
![post php](https://user-images.githubusercontent.com/14994452/34551611-a7e96cd6-f141-11e7-9beb-179e02c2df23.jpg)

**Comment by ravinderk** [comment]
@Sidsector9 I merged PR into core but you did not clear code properly. Please revisit old pr and remove code.

Rename `range_slider` to `donation_limit`

For Ref: https://github.com/WordImpress/Give/pull/2666
