### ISSUE TITLE
Donation Goal amount is reduced when thousands separator is set to a period

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1982]
## Issue Overview
Setting the thousands separator to a period still seems to be problematic for our users in various ways. IN this case, when the thousands separator is a period and the decimal separator is a comma, the goal doesn't save correctly.

## Expected Behavior
The amount should never change upon save.

## Current Behavior
The goal amount changes after saving the form when the thousands separator is set to a period.

## Steps to Reproduce (for bugs)
1. Set the thousands separator to a period. Optionally also set the decimal separator to a comma.
2. Create a form with a goal that is 1,000 then save the form
3. Upon refresh, check the goal and it will now be 1.

Also, when XDebug is on, you should see this PHP warning as well:
Notice: A non well formed numeric value encountered in ...\wp-content\plugins\give\includes\formatting.php on line 113

## Related Issues and/or PRs
https://github.com/WordImpress/Give/issues/1981

## Todos
- [ ] Confirm this fix for the goal amount.
- [ ] Confirm on #1981 as well (the multi-level amounts)
- [ ] Confirm the fix works for the "Set Donation Amount" field
- [ ] Confirm the fix works for the "Minimum Amount" field

**Comment by DevinWalker** [comment]
Reopening since @mehul0810 found a bug:
![](http://g.recordit.co/RQ8f0nJKk4.gif)

**Comment by raftaar1191** [comment]
@DevinWalker 
Found Another bug
please see the video `http://screencast-o-matic.com/watch/cbQirwIQHv`

**Comment by raftaar1191** [comment]
@DevinWalker 

When setting **Thousands Separator** as empty it adding a space with the Amount
![image](https://user-images.githubusercontent.com/22215595/30187330-d7d45184-9446-11e7-8c47-306fac94759f.png)

Is this an issue?

**Comment by raftaar1191** [comment]
Another Bug in the dashboard page of All Forms
-> Working Fine


When setting Thousands Separator as empty it adding a space with the Amount
->we support `space` as thousand separator as some number system have that

**Comment by mathetos** [comment]
Just tested this, looks really solid guys. Great work!
