### ISSUE TITLE
epic(donation): enable sequential ordering

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#244]
## User Story

As an admin, I want sequential donation IDs so that I can satisfy the legal and accounting needs of my organization.

## Current Behavior

I currently have donation IDs based on the post ID which means there are large gaps between numbers that make it appear as if there might be missing donations from an accounting perspective.

## Expected Behavior

I expect to have sequential donation IDs without gaps between them.

European countries, and Canada require that transaction ID numbers be sequential. This isn't currently supported in Give. EDD and WooCommerce both did serious work to make that possible in both of their plugins.

### Resources

- [EDD Advanced Sequential Ordering Extension](https://easydigitaldownloads.com/downloads/advanced-sequential-order-numbers/)
- [Long Support Thread at EDD on their process](https://easydigitaldownloads.com/forums/topic/sequential-numbering/)
- [Ticket in EDD Github with links to their commits](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/2020)
- @chriscct7's [list for their approach to making it happen is very instructive](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/2020#issuecomment-35322424)
- [WooCommerce Sequential Ordering extension](https://wordpress.org/plugins/woocommerce-sequential-order-numbers/)
- https://www.canadiancharitylaw.ca/blog/cra_release_registered_charities_newsletter_no._33_-_information_on_receipt

### Support Tickets

- https://secure.helpscout.net/conversation/489032824/12578/?folderId=848135
- https://secure.helpscout.net/conversation/489032824/12578/?folderId=672199
- https://secure.helpscout.net/conversation/377605708/8176/?folderId=672199
- https://secure.helpscout.net/conversation/377605708/8176/?folderId=672199

**Comment by mathetos** [comment]
This site claims that Sequential Ordering is "best practice" but not a legal requirement in Canada:

http://www.canadiancharitylaw.ca/blog/cra_release_registered_charities_newsletter_no._33_-_information_on_receipt

**Comment by DevinWalker** [comment]
I'm bumping off to `1.9`

**Comment by Benunc** [comment]
A user requested this today, but didn't make it sound like a legal requirement.

**Comment by mathetos** [comment]
We still get regular requests for this. I also notice that it's included in EDD Core now, so potentially we'd have a leg-up to get this started:

![image](https://cloud.githubusercontent.com/assets/930724/25690078/886346b8-3042-11e7-98db-d8400e2c611b.png)

**Comment by Benunc** [comment]
another request for this today.

**Comment by mathetos** [comment]
Another one from Canada today:
https://secure.helpscout.net/conversation/414822910/9634/?folderId=672199

**Comment by Benunc** [comment]
Another request for this today: https://secure.helpscout.net/conversation/489032824/12578/?folderId=848135

**Comment by Benunc** [comment]
A pain point for users here is that whatever solution we come up with be retroactive: They need to be able to provide proof to the authorities of past donations, not just going forward.

**Comment by Benunc** [comment]
More context from the user: 

> Sequential number is a best practice at al, it is required by law. The reason is that making a donation gives tax advantage, when we make donation we can deduct 60 % of the amount given on our income tax (for person) or company tax (for company) ; both companies and person are controlled by tax authorities and need to justify the amount given which gave tax advantage.
> But association who takes donations are also controlled and must give proof of all donations. In order to control all money which is coming in sequential number are compulsory, if you have a sequential number missing between 2 receipts, tax authorities will understand that you try to hide money from them ; all system to justify money for donations or invoice must have a sequential number.
> The number on the proof of donor side and our side must be the same so we have no way to trick your system to have our sequential number because that would mean on donors side, the number will not be the same than ours.
> That is a serious and very urgent issue !
> That is not only for my country (France) that is for all Europe ; I have business in Belgium, Switzerland, France and UK, all those countries works the same.
> I have made a bit of research for you here's a link I found on Europa offical invoice giving information that must be on an invoice (receipt is like invoice) https://ec.europa.eu/taxation_customs/business/vat/eu-vat-rules-topic/vat-invoicing-rules_en
> Go to the part What information must an invoice contain?
> Information required in all cases
> 
> • Date of issue
> • Unique sequential number identifying the invoice
> 
> 
> 
> Here's a website specialiszed on "recu fiscaux" (receipt for association / donation) http://www.recus-fiscaux.com/edition-recus-fiscaux/format-contenu that is in french
> • Un numéro d'ordre : Numéro unique pour chaque reçu, comme sur une facture. = sequential number
> 
> Here's an other on Belgium, official website of tax authorities https://finances.belgium.be/fr/asbl/dons/recus#q2
> COMMENT LES REÇUS ENVOYÉS AUX DONATEURS DOIVENT-ILS ÊTRE RÉDIGÉS ? (how receipt must be sent to donors)
> le numéro d'ordre
>

**Comment by ravinderk** [comment]
@kevinwhoffman @DevinWalker 
There is the following task which has to done to complete this issue:

**1. Logic integration with core:**
- [ ] Store donation number as donation title and meta (need discussion).
- [ ] Display donation number on donation listing page
- [ ] Display donation number on View Donation Details
- [ ] Display donation number on donation receipt
- [ ] Display donation number on donation receipt email
- [ ] Display donation number in donation history (for a donor)
- [ ] Display donation number in log listing page
- [ ] Add donation number to support for history export ()

**2. Admin Setting and integration:**
- [ ] Enable/Disbale setting
- [ ] Add Prefix Support
- [ ] Add Suffix Support
- [ ] Add Sequential order numbering (start from largest donation number on existing install if active)
- [ ] Add start from option [ start from 1 for feash install if enbaled] 
  - [ ] Add the minimum number of donation number count for the donation number for ex 1000, 01000, 001000.
- [ ] Date tag support for prefix and suffix

**3. API for the developer:**
- [ ] Search donation by donation number
- [ ] Find donation by donation number
- [ ] Get donation number by donating id and vise versa

**4. Update script if need ( need to discuss)** 
- [ ] Evaluate update script

**5. Test add-on compatibility:**
- [ ] Test with payment gateways
- [ ] Test with recurring donation

**Comment by kevinwhoffman** [comment]
> A pain point for users here is that whatever solution we come up with be retroactive: They need to be able to provide proof to the authorities of past donations, not just going forward.

@Benunc @mathetos I want to clarify that retroactive sequential numbering will not be part of our scope. Massive technical challenges aside, I don't think we should encourage it. Once a donation ID has been displayed, emailed to, or printed by the donor, then the ID should be considered permanent. Allowing site admins to renumber existing donation IDs would break the connection between their records and the donors records. I don't believe we should ever allow that connection to be compromised.

See #2913 for the current settings we have planned to get a sense of what is part of our scope. Admins with existing donations will be able to begin sequential ordering based on the ID of their last donation or a custom ID. While admins without donations will begin sequential ordering starting at `1`.

**Comment by mathetos** [comment]
@kevinwhoffman totally agree that retroactive sequential ordering is out of scope and not recommended.
