### ISSUE TITLE
fix(compat): prevent missing donation data with Restrict Content Pro

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#2710]
## Issue Overview

If you activate [restrict content pro](https://github.com/restrictcontentpro/restrict-content-pro) then you will see information missing on donation listing page in admin.

![image](https://user-images.githubusercontent.com/1784821/35374039-3db805f2-01c7-11e8-9812-2787cfdaab2d.png)

## Related

- https://secure.helpscout.net/conversation/543868415/15603?folderId=672197
- https://secure.helpscout.net/conversation/546042810/15768/

## Tasks
- [x] Implement solution
    - [x] Renaming the meta type` payment` to `donation`
    - [x] Renaming the table `{*}_give_paymentmeta` to `{*}_give_donationmeta` 
    - [x] Renaming the table and `payment_id` -> `donation_id` column
    - [x] Rename `$wpdb` property `paymentmeta` -> `donationmeta`
    - [x] Add DB upgrade
    - [x] Add backward compatibility 
- [x] Tests
    - [x] Check DB upgrade
    - [x] Test with multiple addon
- [x] Add blog post
- [x] Add issue for document update

**Comment by ravinderk** [comment]
@DevinWalker 
### Cause of issue:
I found the conflict between RCP and Give. We have same `$wpdb->paymentmeta` table name param, so restrict content pro overwriting over table name or vice versa  :disappointed:
For ref:
https://github.com/WordPress/WordPress/blob/master/wp-includes/meta.php#L931
https://github.com/restrictcontentpro/restrict-content-pro/blob/master/restrict-content-pro.php#L371

**Comment by samsmith89** [comment]
Having this issue currently with a customer. Was this fixed and reopened, or still waiting?

**Comment by kevinwhoffman** [comment]
@ravinderk Please complete the following tasks but do not move forward with implementation until we discuss with @DevinWalker.

- [ ] Post a possible solution in this issue, including whether a database upgrade routine would be necessary.
- [ ] Update the task list based on your proposed solution.
- [ ] Update the story point estimate based on your proposed solution.
- [ ] Notify @DevinWalker and @kevinwhoffman to discuss next steps.

**Comment by ravinderk** [comment]
@kevinwhoffman I already explained the problem here: https://github.com/WordImpress/Give/issues/2710#issuecomment-360382971

`paymentdata` is not a general table name prefix that was logic behind keeping. But conflict with `Restrict content pro` prove that In future, we will have the possibility to conflict with a plugin which can process payment own there own.

Thanks to `Restrict content pro` team which took the first step to resolve conflict (release/3.0): https://github.com/restrictcontentpro/restrict-content-pro/issues/1656

To resolve this problem we can take following steps:
- [ ] Rename meta type `payment --> donation` : https://github.com/WordImpress/Give/blob/36231565464706a8ebc00156ed1ab705c04b97fb/includes/class-give-db-payment-meta.php#L41
- [ ] Rename table `{*}_give_paymentmeta --> {*}_give_donationmeta`: https://github.com/WordImpress/Give/blob/36231565464706a8ebc00156ed1ab705c04b97fb/includes/class-give-db-payment-meta.php#L53
- [ ] Add upgrade routine to rename table and `payment_id --> donation_id` column

**Comment by kevinwhoffman** [comment]
@ravinderk Thanks for the breakdown. RCP seems to have merged a fix on their end, but it is not slated for release until RCP 3.0, which does not look like it has a known release.

From our end, this does not look like a minor fix, so I'd like to hear from @mathetos how many users this is affecting. Then we can discuss timeline.

**Comment by mathetos** [comment]
@kevinwhoffman Only two customers reporting as far as I've seen so far. But the urgency is related to the fact that Give 2.0+ is completely unusable for any user that is also running RCP. Additionally, I can imagine this problem would happen with other plugins that call `paymentmeta` using wpdb as well.

**Comment by Benunc** [comment]
This issue also breaks functionality with Zapier and Give, and I have a user reporting that, and I replicated the problem on my test (live) install. 

## Findings
WHen RCP and Give are active on the same site, in addition to the above reference (donor missing) issue, Zapier is unable to connect to the api URL at all.

Additionally, the API returns incomplete and incorrect information:

Before activating RCP:
____________
![screen shot 2018-04-04 at 4 11 42 pm](https://user-images.githubusercontent.com/9629102/38332081-196f1da6-3823-11e8-87f8-5b0307c1f6f0.png)
____________
After Activating RCP:
____________
![screen shot 2018-04-04 at 4 12 12 pm](https://user-images.githubusercontent.com/9629102/38332115-2ee61d9c-3823-11e8-9858-87295653ed84.png)
____________
So, in addition to removing all relevant data from the API, it also incorrectly attributes the donations to the POST "Thought 53" which isn't a form at all.

**Comment by ravinderk** [comment]
@WordImpress/support I think this issue fixed with latest https://github.com/restrictcontentpro/restrict-content-pro/releases/tag/2.9.12

I tested it. Can you confirm?

**Comment by samsmith89** [comment]
I will check on this today.

**Comment by mathetos** [comment]
@ravinderk Two things:
1) It looks like that PR on RCP was merged into version 3.0, but that's not their current release.
2) Even if they fix it on their end, I believe we need a way to avoid this happening with other plugins as well. Is there any prefixing or namespacing we can do to avoid this problem in the future?

**Comment by ravinderk** [comment]
@mathetos yes, I will be fixing in release assign to this issue.

**Comment by mehul0810** [comment]
@ravinderk I can see an issue on `2.2` Give core branch even after running DB upgrade.
![image](https://user-images.githubusercontent.com/1852711/40613937-3a50536e-629e-11e8-891e-18f0f4bb33af.png)

**Comment by ravinderk** [comment]
@mehul0810 Close this issue because it fixed.
