### ISSUE TITLE
feat(admin-tool): merge CSV toolbox into Give core

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2875]
## Issue Overview
The CSV toolbox has proven useful enough to be merged into core: https://github.com/WordImpress/Give-CSV-Toolbox

## Task List
- [x] Remove the old Give Donation History functionality 
- [x] update code to support with Give 2.0 DB upgrade 
- [x] Add export Donation Link to submenu pages that export Donation History 
- [x] Update Give-CSV-Toolbox functionality so admin can select all form option and then export the donation ( Hide FFM, Custom Filed and Hidden Custom Field Columns when all Donation form is selected from DropDown  )
- [x] Add export Donation Link to submenu pages that export Donation History 
- [x] Let's also make sure that FFM, Custom Filed, and Hidden Custom Field Columns sections only display if there is actually a checkbox available within the section
- [x] Fix issues https://github.com/WordImpress/Give/issues/2978 ( Issues closed not able to reproduce the issues again )
- [ ] Delete Give-CSV-Toolbox repository and write a blog post about it 

## Related Issues

- [x] https://github.com/WordImpress/Give-CSV-Toolbox/issues/7
- [ ] https://github.com/WordImpress/Give/issues/2978

**Comment by raftaar1191** [comment]
Hey @DevinWalker @ravinderk @kevinwhoffman Need your help with UI 

Here I am thinking of adding a new option to **Export** called  `Export Donation History on per Form Basic` like we have done in **Import** tab where we have to click on a button and a new page open up ( Submenu ) and then it will contain the setting to export the CSV


Video Link: https://screencast-o-matic.com/watch/cFeUXsDp3K

![image](https://user-images.githubusercontent.com/22215595/38087347-601e107a-3375-11e8-99d3-260cdb0ab0d5.png)

![image](https://user-images.githubusercontent.com/22215595/38087316-4fbfd84e-3375-11e8-9c50-99fbe90e21f6.png)

**Comment by kevinwhoffman** [comment]
@raftaar1191 @DevinWalker I think you are on the right track with your recommendation, but I would like to avoid having two different options to export Donation History. I think we should be able to handle it all through the CSV toolbox UI. Please see the video below and the updated tasks on this issue.

https://drive.google.com/open?id=1o4J-Z669aKS4v6Un-dXqjdYFWbFtMHWj

**Comment by raftaar1191** [comment]
Slack Call Summary

Participants: @devinwalker, @raftaar1191
Topic: Plan for the UI and for [2964](https://github.com/WordImpress/Give/issues/2964)
Result: Had a call with @DevinWalker on the above issues and come to the conclusion that we are going to remove the old Give Donation History functionality  and replace it with [Give-CSV-Toolbox](https://github.com/WordImpress/Give-CSV-Toolbox) so we don't need to fix [2964](https://github.com/WordImpress/Give/issues/2964) we are going to remove this 
About UI we are going to follow the [above mention UI](https://github.com/WordImpress/Give/issues/2875#issuecomment-377362329) that is being suggested @kevinwhoffman

**Comment by Benunc** [comment]
I've updated the number reported label here, and want to also add some user insight. 

The main sticking point with Donor exports (and the only thing for which the workaround is "you'll have to manually merge two CSVs" is how billing address data is currently handled. If a Donor is also a WordPress user, donor data exports will export address data. If the donor is not a user, no address data is exported, because address data is currently tied only to WP user, or to Donation, not Donor.

Since the advent of the CSV toolbox, this is the most glaring pain point left in terms of donor data export.
