### ISSUE TITLE
refactor(form): simplify usage of localized variables for js

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2895]
## User Story
As a developer, I want some of the localized variables which are general must be defined in `give_global_vars` instead of add-on specific localized variables. 

This will help the developer to access and use already listed localized vars in add-ons rather than duplicating the same localized vars in the scope of the add-on.

## Current Behavior
I currently can see that there are some of the localized variables in Stripe Add-on which must have to be included in Give Core. 

**Duplicate Localized Variables:**
1. number_decimals
2. loading
3. give_version

**Localized Variables which can be part of Give Core**
1. `give_version` to be converted to `version` under `give_global_vars`
2. `loading` should have only text `Loading` instead of `Loading...`. We can add `...` when we use the localized variable

![image](https://user-images.githubusercontent.com/1852711/37266964-a03e4246-25e3-11e8-8c80-12aa524808b6.png)

## Expected Behavior
I expect to remove duplicates and add general localized variables to Give Core.

## Possible Solution
We need to check for all the add-ons and finalize the list of localized variables to be included in Give Core in order to remove duplicates from add-ons

## Tasks
- [ ] Research Core and Add-ons
- [ ] Identify the localized variables which can be part of Give Core.
- [ ] Remove unnecessary and duplicate localized variables from the add-on.
- [ ] Testing

## Environment
<details>
    <summary>WordPress System Info</summary>
    ### WordPress Environment ###

Home URL: http://give.test
Site URL: http://give.test
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, wc-pending, wc-processing, wc-on-hold, wc-completed, wc-cancelled, wc-refunded, wc-failed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.test
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.2.0
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.0.7
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access✔Donor Gratitude
Upgraded From: 2.0.3
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give.test/donation-confirmation/
Failure Page: http://give.test/donation-failed/
Donation History Page: http://give.test/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Stripe - Credit Card
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - Currency Switcher: ❌ Unlicensed – by WordImpress – 1.0.2
Give - eWay: ❌ Unlicensed – by WordImpress – 1.0
Give - Stripe Gateway: ❌ Unlicensed – by WordImpress – 1.5.2

### Other Active Plugins ###

Gutenberg: by Gutenberg Team – 2.3.0
Snippet Library: by  – 1.0
WooCommerce: by Automattic – 3.3.3
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.5.2
WooCommerce Stripe Gateway: by WooCommerce – 4.0.7

### Inactive Plugins ###

Give - Form Field Manager: by WordImpress – 1.2.8
Give - PDF Receipts: by WordImpress – 2.2.2
Give - Recurring Donations: by WordImpress – 1.5.7
Give - Square: by WordImpress – 1.0
Loco Translate: by Tim Whitlock – 2.1.0
Polylang: by Frédéric Demarle – 2.3.1
W3 Total Cache: by Frederick Townes – 0.9.6

### Active MU Plugins ###

Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X </li>
        <li>Version: 10.12.6</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Safari | IE | Edge</li>
        <li>Version: any</li>
    </ul>
</details>

**Comment by mehul0810** [comment]
As discussed with @ravinderk over the call, we can remove usage of currency related variable from `give_global_vars` due to the fact that we need dynamically populated data there which is not feasible with localized variables. We have achieved this using data attributes added to donation form tag. 

**Deprecate Usage:**
![image](https://user-images.githubusercontent.com/1852711/37271620-99e46220-25f9-11e8-99b9-a85a4b347c27.png)

**Start using:**
![image](https://user-images.githubusercontent.com/1852711/37271638-b41b4762-25f9-11e8-8e08-1e345cd671c3.png)

**Comment by raftaar1191** [comment]
@mehul0810 @ravinderk 

What about the backward dependency for Give or Third Party Add-on. We should consider that too.

At least we should first released some blog post so that third-party developer will come to know about this.

**Comment by mehul0810** [comment]
@DevinWalker @ravinderk @kevinwhoffman 
I have simplified the localized variables with my findings. Please check my findings and let me know your thoughts on changing the localized variables.

We can research in all the add-ons to simplify usage of localized variables and create an issue in each add-on where required.

**Note:** There are chances that updating the localized variables in the core plugin can break some functionality in add-ons. So, we need to update required add-ons as well.

### My Findings on Localized Variables of Give Core

**For `give_global_vars`:**
1. :x: `ajaxurl` - _Remove it from here. We can use `ajax_url` from a pre-defined localized variable_ 
2. :white_check_mark: `checkout_nonce` - _This nonce should only be used for processing donations. We can also rename this variable name to `donation_nonce`_
3. :x: `currency`, `currency_sign`, `currency_pos`, `thousands_separator`, decimal_separator`, `number_decimals` - _We are loading the number decimals as data-attribute in `<form>`. Hence, we should ensure that all the add-ons are using it as data-attribute instead of a localized variable and then we can remove it_
4. :x: `no_gateway`, `bad_minimum`, `confirm_email_sent_message` - _I think for validation texts either we create a separate localized variable or can use a different workaround. Hence, we should remove this_
5. :x: `general_loading`, `purchase_loading` - _We should use loading text from `give_scripts.loading` and remove this from here. Also, we can provide an ability for the developer to change the text of loading throughout the Give plugin._
6. :white_check_mark: `give_version` - _We should rename it to `version` and use it in add-ons whenever required as I have noticed that Stripe add-on is also loading `give_version`. Hence, i think it should be within core and add-ons should call it from the core plugin itself_ 
7. :heavy_plus_sign: `sitename` - _I have noticed that Stripe add-on is having this localized variable. Hence, I think it should be moved to Give Core and can be called from the core plugin_
8. :white_check_mark: `magnific_options` - _Keep it as it is_
9. :white_check_mark: `form_translation` - _I think this is added for translation purpose when we switch gateway which replaces HTML using AJAX. I think we are planning to refactor that switching gateway part. So, we can remove this at that time and keep it as it is for now_

**For `give_scripts`:** 
1. :white_check_mark: `ajaxurl` - _Use the ajax URL from here_ 
2. :white_check_mark: `ajaxNonce` - _Use nonce for ajax calls from here_
3. :white_check_mark: `loading` - _Use loading text from here_
4. :x: `select_option` - _I think for validation texts either we create a separate localized variable or can use a different workaround. Hence, we should remove this from here_
5. :x: `default_gateway` - _I think this is not required in a localized variable as it is dynamic using ajax which will not reflect the exact selection of gateway and can misguide the third-party developer. Hence, we should remove this and add it as data-attribute to `<form>`_
6. :x: `permalinks` - _This is not used in core and most of the addons I have checked with quick file search. Finalize that this localized variable is not in use then remove it_
7. :x: `number_decimals` - _We are loading the number decimals as data-attribute in `<form>`. Hence, we should ensure that all the add-ons are using it as data-attribute instead of a localized variable and then we can remove it_

**Comment by kevinwhoffman** [comment]
> What about the backward dependency for Give or Third Party Add-on. We should consider that too.

I agree with @raftaar1191 that we need to be very careful of breaking compatibility with third-party implementations that may rely on these variables. There are valid points here which could ideally simplify the local variables, but we don't have the luxury of starting from scratch.

@mehul0810 Thanks for your efforts in the research, but I am closing this as I don't see a path forward without breaking compatibility with third parties.
