### ISSUE TITLE
build(composer): commit composer.lock file

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#2896]
## User Story

As a developer, I want the `composer.lock` file to be committed in Git so that I can reliably recreate a snapshot of Give's dependencies from any given commit.

## Current Behavior

I currently cannot know whether fellow developers are developing with the same versions of Give's dependencies even if we are on the same branch and the same commit. That's because if `composer.lock` is not available, Composer will generate a new lock file using the latest allowed versions as defined in `composer.json`.

## Expected Behavior

I expect to have a `composer.lock` file available when I clone any Git project that uses Composer.

## Possible Solution

Commit `composer.lock`.

## Related

- https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control
- https://stackoverflow.com/questions/12896780/should-composer-lock-be-committed-to-version-control

## Tasks

- [x] Review the dependency versions defined in `composer.json`.
- [x] Generate the `composer.lock file`.
- [x] Commit the lock file.
