### ISSUE TITLE
Evaluate existing Give-Display-Donors shortcode for functionality

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2899]
## Task List

- [ ] Review https://github.com/WordImpress/Give-Display-Donors
- [ ] Determine if it's forkable
- [ ] Evaluate `class-give-gravatars.php` and either fork or remove

**Comment by kevinwhoffman** [comment]
Closing due to overlap with #2901. We should avoid creating issues that are strictly for research purposes, and instead include research as the first task in a goal-oriented issue.
