### ISSUE TITLE
design(donor): create a list and grid donor wall view

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2900]
## Tasks

- [x] Create list view with the grid, amount raised, comment, and donor name
- [x] Create grid view with options set for basic view
- [x] Allow donors to opt-in to being publicly displayed
- [x] Provide an interface for leaving a comment as well
- [ ] Finalize label, notice, setting description (any text using in this feature )
