### ISSUE TITLE
feat(admin-setting): implement admin setting for sequential ordering 

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#2913]
## User Story
As an admin, I want settings to fine-tune sequential ordering so that I can customize my donation IDs with prefixes and suffixes to my liking.

## Tasks
- [x] Add `Sequential Donation [radio]` setting.
- [x] Add `Sequential Starting Number [number input]` setting (start from largest donation number on existing install or 1 for fresh install) (partially done).
- [x] Add `Sequential Prefix [text input]` setting.
- [x] Add `Sequential Suffix [text input]` setting.
- [x] Add support for `{year}` and `{month}` placeholders in prefix/suffix fields.
- [x] Add `Padding [number input]` setting (a padding of `3` would display `1` as `001`).

**Comment by kevinwhoffman** [comment]
Here are some settings screen references from existing sequential ordering plugins.

## [Easy Digital Downloads](https://wordpress.org/plugins/easy-digital-downloads/)

![image](https://user-images.githubusercontent.com/1938671/37390143-4c31fb4c-273d-11e8-9c72-75bbd9fc48a8.png)


## [WooCommerce PDF Invoices & Packing Slips](https://wordpress.org/plugins/woocommerce-pdf-invoices-packing-slips/)

This plugin requires WooCommerce in order to see the settings page.

![image](https://user-images.githubusercontent.com/1938671/37390704-53691ba0-273f-11e8-8974-b531b8aa1b95.png)

**Comment by kevinwhoffman** [comment]
@ravinderk Let's remove the need to include the date in the prefix/suffix. We have not seen a request for that, I don't believe it's very common to include the date in an invoice ID, and it could complicate the UX if we have to account for date formatting. So let's just remove that for now.

I did add an `Annual Reset` setting which has been requested and I do believe will be used more commonly to reset the sequential ordering each new year.

**Comment by ravinderk** [comment]
@kevinwhoffman what will be donation number will look like with when `Annual reset` enabled
`{prefix}number{suffix}{year}`

**Comment by kevinwhoffman** [comment]
@ravinderk See the setting descriptions in this screenshot. I think placeholders for `{year}` and `{month}` will be necessary, and we should allow them to be entered in the prefix/suffix fields. Then the user can place them wherever they want.

![image](https://user-images.githubusercontent.com/1938671/37393535-bbe11086-2747-11e8-92f2-e735ad5aafeb.png)

**Comment by ravinderk** [comment]
@DevinWalker What do you think about `Annual Reset` setting?

**Comment by DevinWalker** [comment]
Annual reset is more advanced functionality that shouldn't be in the base Give functionality. Let's keep that for the future "Advanced" sequential ordering add-on.

**Comment by ravinderk** [comment]
Updated task list as @DevinWalker  suggest in https://github.com/WordImpress/Give/issues/2913#issuecomment-373270047
