### ISSUE TITLE
fix(donation): prevent spam

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#2930]
## User Story

As an admin, I want to prevent spam so that my data remains clean and reports are reliable.

## Current Behavior

I currently experience donation spam in the following ways:

- $0 donation and donor created on forms with registration
- small donation and donor created on forms with registration (pay to spam)
- $0 donation without donor created on forms without registration
- only donor created due to Stop Signup Spam plugin preventing the donation from being created
- spam donors created via the `[give_register]` registration form (maybe a separate issue).

## Expected Behavior

I expect to only see real donations/donors appear in Give.

## Possible Solution

Because of the $0 donations, it appears likely that these spammy donations are the result of direct `$_POST` requests rather that donations made through the form.

1. Confirm that nonce validation is working as expected so that only donations with valid nonce fields are allowed.
2. Test the donation form with JS turned off to check the effectiveness of server-side validation.
3. Check $0 condition immediately after nonce validation so that the submission process can be short-circuited if a valid amount is not included.

### Via front-end form with JS turned off

1. Attempt donation through front-end form with JS turned off. Use $0 as the amount.
2. Verify whether the donation/donor appear in the database and Give admin UI.

### Via `$_POST` request

1. Mimic the `$_POST` request that Give uses to submit a donation. Use $0 as the amount.
2. Verify whether the donation/donor appear in the database and Give admin UI.

### Issues

- feat(form): disallow email address as first name #2862

### Support Tickets

- https://secure.helpscout.net/conversation/512632384/13580/?folderId=672199
- https://secure.helpscout.net/conversation/544347556/15660/?folderId=672197

## Tasks

- [x] Recreate a $0 donation via front-end form with JS turned off and report results in this issue.
- [x] Recreate a $0 donation via `$_POST` using Postman and report results in this issue.
- [x] Improve server-side validation to prevent spam.
- [x] Confirm that spam is stopped through front-end donation form with JS turned on.
- [x] Confirm that spam is stopped through front-end donation form with JS turned off.
- [x] Confirm that spam is stopped through direct `$_POST` request.

**Comment by kevinwhoffman** [comment]
@raftaar1191 Please start by trying to recreate the $0 donations through the front-end form and as a `$_POST` request. Report here what you find. Thanks.

**Comment by raftaar1191** [comment]
## Finding
I have tested this out with Disable the JS and also Postman I come to a point that we check for Donation minimum amount check when we donated the amount and if the custom amount is disabled the minimum donation amount is zero 

## What we can do
When we check for the minimum donation amount conditions and the custom amount option is disabled then we should get the minimum amount from the Donation level if the **Donation Option** option is set as **Multi-level Donation** or if the **Donation Option** is set as **Set Donation** then we should pick the value from **Set Donation** input box


We can use the [give_get_lowest_price_option](https://github.com/WordImpress/Give/blob/release/2.0.7/includes/forms/functions.php#L683) function to get the form minimum donation amount 

We should call give_get_lowest_price_option function at the time of fetching the [donation form minimum value](https://github.com/WordImpress/Give/blob/release/2.0.7/includes/class-give-donate-form.php#L535)  in class method called `get_minimum_price`

**Comment by kevinwhoffman** [comment]
**Slack Call Summary**

Participants: @raftaar1191, @kevinwhoffman
Topic: Discuss how $0 donations are being prevented
Result: Deepak concluded that the form minimum was being set to `0` under certain circumstances and that $0 donations could be made with JS disabled. Deepak has submitted a PR to prevent the form minimum from being set to `0`.

Deepak was unable to make a donation through a direct `$_POST` request in Postman due to nonce verification. This is a good thing; it means our nonce verification is working.

cc: @mathetos

**Comment by mehul0810** [comment]
@kevinwhoffman I've created a new [issue](https://github.com/WordImpress/Give/issues/3050) on preventing donation/donor spams as I have set up a customized form in PHP to send spam and it is going through with test donations.
