### ISSUE TITLE
fix(form): Add shortcode support to Offline Donations Instructions output

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2937]
## User Story

As an admin, I want to output content from other plugins via a shortcode into my Offline Donations instructions so that I can have more flexibility in the instructions presentation.

User highlighted this problem here:
https://wordpress.org/support/topic/enable-shortcodes-in-offline-instructions/

## Current Behavior
I currently cannot do that, see here:
![image](https://user-images.githubusercontent.com/930724/37716514-f1d57954-2cdb-11e8-90cb-6622b86cf00c.png)

## Expected Behavior
I expect that what appears in the admin, would appear on the frontend as well. The shortcodes render in the admin correctly, but not the front-end. See here:
![image](https://user-images.githubusercontent.com/930724/37716573-0f46fd46-2cdc-11e8-9dde-0ae5b0b46a8d.png)

I also expect that if this isn't currently available, I can customize this with a filter, but that also appears to be unavailable.

## Possible Solution

Use `apply_filters('the_content');`

Change this line:
https://github.com/WordImpress/Give/blob/release/2.0.7/includes/gateways/offline-donations.php#L469

To this:
`$global_offline_instruction = apply_filters('the_content', give_get_option( 'global_offline_donation_content' ));`

## Steps to Reproduce
1. Insert a shortcode into either the global Offline instructions, or the per-form instructions
2. View the instructions on the front-end and you'll see the naked shortcode

## Related
- https://github.com/WordImpress/Give/issues/68

## Tasks
- [x] Implement the code change cited above.
- [x] Ensure the results are the same for both the Global Offline content, and the per-form Offline content.
- [x] Review all other WYSIWYG outputs throughout Give core for anywhere that we don't use the `the_content` filter and update as well. We should ensure that the frontend output matches expectations with the backend, and this issue has come up previously (see "Related" above).
- [x] Consider adding additional filters to the output for further customization.
