### ISSUE TITLE
fix(donation): ensure donation completes if permalink begins with `index.php`

### ISSUE THREAD

**Issue by PauldeKoning** [WordImpress/Give#2941]
## User Story

As a `user`, I want `to donate`.

Trying to donate as a user won't work cause of a 404 error after pressing on the submit button.

## Current Behavior

Currently I get a 404 page after pressing the 'Donate' button because the POST request goes towards the URL: localhost/wordpress/donations/yes/?payment-mode=manual

## Expected Behavior

The post request, because the permalink starts with /index.php/, should go to localhost/wordpress/index.php/donations/yes/?payment-mode=manual

## Possible Solution

Create a check to check if the permalink starts with a page (.php) and if it does, make sure to add it onto the base wordpress link (localhost/wordpress + permalink_pagename) in the form's action tag

## Steps to Reproduce

1. set permalink to /index.php/%year%/%post_id%/ (any other tags will do)
2. submit a donation form
3. get 404 page

## Environment

<details>
    <summary>WordPress System Info</summary>
    ### WordPress Environment ###

Home URL: http://localhost/wordpress
Site URL: http://localhost/wordpress
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /index.php/%hour%/%day%/%year%/%post_id%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: localhost
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.28-0ubuntu0.16.04.1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
PHP Max Upload Size: 2 MB
cURL Version: 7.47.0, OpenSSL/1.0.2g
SUHOSIN Installed: –
MySQL Version: 5.7.21
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ❌ Your server does not have the DOMDocument class enabled - HTML/Multipart emails, and also some extensions, will not work without DOMDocument.
gzip: ✔
GD Graphics Library: ❌
Multibyte String: ❌ Your server does not support the mbstring functions - this is required for better character encoding. Some fallbacks will be used instead for it.
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.0.6
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://localhost/wordpress/index.php/donation-confirmation-2/
Failure Page: http://localhost/wordpress/index.php/donation-failed-3/
Donation History Page: http://localhost/wordpress/index.php/donation-history-3/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Inactive Plugins ###

Akismet Anti-Spam: by Automattic – 4.0.2
Hello Dolly: by Matt Mullenweg – 1.6

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Ubuntu</li>
        <li>Version: 16.04 LTS</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
        <li>Version: 65</li>
    </ul>
</details>

**Comment by kevinwhoffman** [comment]
@raftaar1191 Please confirm if you're able to recreate and then adjust your estimate as necessary.

**Comment by raftaar1191** [comment]
@kevinwhoffman @PauldeKoning @Benunc 
I try to regenerate the issue at my end but I am not able to regenerate the issue

## Task
- [ ] Testing in Apache and Nginx 
- [ ] Testing in PHP 5.3 as well as in 7.1
- [ ] Testing by making donations as admin an as well as donor
- [ ] Testing by pasting the Donation form shortcode in Pages and then making the donation from that page
- [ ] Testing by using **give_form_grid** shortcode in pages too but still not able to reproduce the issues 


Here is the Video on how I have tested this issue: https://screencast-o-matic.com/watch/cF116gbSlU

**Comment by raftaar1191** [comment]
@kevinwhoffman @PauldeKoning @Benunc 
I try to regenerate the issue at my end but I am not able to regenerate the issue

## Task
- [x] Testing in Apache and Nginx 
- [x] Testing in PHP 5.3 as well as in 7.1
- [x] Testing by making donations as admin an as well as donor
- [x] Testing by pasting the Donation form shortcode in Pages and then making the donation from that page
- [x] Testing by using **give_form_grid** shortcode in pages too but still not able to reproduce the issues 


Here is the Video on how I have tested this issue: https://screencast-o-matic.com/watch/cF116gbSlU

**Comment by raftaar1191** [comment]
@mathetos Can you please have a look at this issues. I am not able to regenerate this issue at my end 

I am moving this issues in the blocker pipeline

**Comment by raftaar1191** [comment]
Hey, @PauldeKoning I try to regenerate this issue in my local environment by using the local by flywheel but not able to regenerate the issues.

Can you kindly provide us with some details of your local environment or else some video on how we can regenerate this issue?

**Comment by PauldeKoning** [comment]
Hello, sorry for the late reply.

I have managed to recreate the issue in `Apache/2.4.18 (Ubuntu) Server at localhost Port 80` using PHP 7.0.30.

What I have done is set my wordpress permalink to `/index.php/%hour%/%day%/%year%/%post_id%/` via custom structure.
![screenshot from 2018-06-12 13-33-58](https://user-images.githubusercontent.com/22085826/41288076-567580a2-6e45-11e8-9de4-9f03c5a3d759.png)


This turns the permalink of the donation form into `http://localhost/wordpress/index.php/donations/[name]/` in this case `http://localhost/wordpress/index.php/donations/amazing-form/`
![screenshot from 2018-06-12 13-33-42](https://user-images.githubusercontent.com/22085826/41288082-5bbd9afe-6e45-11e8-9a6c-24614884efe4.png)

Then when I look in the code of the actual form, the index.php is not in the action attribute.
![screenshot from 2018-06-12 13-32-56](https://user-images.githubusercontent.com/22085826/41288108-75f7345c-6e45-11e8-85ae-415e6b8adfa4.png)

**Comment by kevinwhoffman** [comment]
@PauldeKoning Can you give us some insight as to why `index.php` is part of your permalink so we can help you resolve this? Thanks.

**Comment by raftaar1191** [comment]
Slack Chat Link: https://givewp.slack.com/archives/C0FAGC83C/p1528861416000165

**Comment by kevinwhoffman** [comment]
Closing as inactive. We'll re-open if we get more information regarding the use case of `index.php` in the URL.
