### ISSUE TITLE
feat(grid): improve UX/UI of donation form grid

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#2943]
## User Story

As a developer, I want to display the donation form grid via CSS Grid instead of Flexbox so that my galleries can respond to the available space.

There are also a number of shortcode attributes that should be added so that users have control over their form grids.

## Current Behavior

I currently use Flexbox and have to specifically choose the max number of columns rather than allowing the gallery to determine its own best fit. My layout options are also limited as Flexbox excels at one-directional layouts whereas Grid excels at two-directional layouts.

## Expected Behavior

I expect to use CSS Grid as it is the future of grid-style layouts on the web and should be introduced early before third-party developers start customizing styles based on another approach.

## Possible Solution

Replace the current Flexbox layout with CSS Grid and add a `Best Fit` default style that lay out grid items according the available space.

### Issues

- feat(form): display multiple forms in a grid #1414 #2783
- design(donor): create a list and grid donor wall view #2900

### Resources

- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout
- https://www.youtube.com/watch?v=FEnRpy9Xfes
- https://www.youtube.com/watch?v=dQHtT47eH0M

## Tasks

- [x] Replace Flexbox with CSS Grid for the donation form grid layout.
- [x] Style according to `Best Fit` by default.
- [x] Add fallback styles for browsers that don't support Grid.

**Comment by kevinwhoffman** [comment]
![image](https://user-images.githubusercontent.com/1938671/37814576-0966e7b8-2e41-11e8-98d1-d640a961321f.png)

**Slack Call Summary**

Participants: @devinwalker, @kevinwhoffman
Topic: Review Donation Form Grid styles and behavior
Result: New Grid styles are in place and the overall direction has been approved. Remaining tasks include:

**Kevin's Tasks for this Issue**

- [ ] Style pagination.
- [ ] Clarify shortcode attribute names.
- [ ] Add shortcode attribute to define number of forms displayed.

**Sid's Tasks in New Issue**

I'm documenting these here temporarily until I can create a new issue.

- [ ] Generate excerpt from form content if the excerpt field is empty.
- [ ] Load modal forms via AJAX rather than hiding every form on the page.

**Comment by kevinwhoffman** [comment]
**Slack Call Summary**

Participants: @mathetos , @kevinwhoffman
Topic: Review shortcode name and attributes
Result: Matt and Kevin discussed shortcode attributes and decided on the following list:

**[give_form_grid]**

- `columns="best-fit"` [best-fit|1|2|3|4]
- `show_title="true"` [true|false]
- `show_goal="true"` [true|false]
- `show_excerpt="true"` [true|false]
- `show_featured_image="true"` [true|false]
- `link="redirect"` [redirect|modal]
- `forms_per_page="12"` [int]
- `ids=""` [comma-separated ids]
- `cats=""` [comma-separated form categories]
- `tags=""` [comma-separated form tags]
