### ISSUE TITLE
fix(donation): polish sequential ordering

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#2952]
## User Story

As a Give developer, I want the following feedback addressed so that we avoid future support issues.

## Current Behavior

I currently...

- Cannot set the starting number to whatever I want.
- Get annoyed having to unlock every field in the Sequential Ordering settings page.
- Am concerned that the `post_name` in the database is assigned a value equal to the sequential order, such as `3`. If another post with the slug `3` already exists, then it would receive the slug `3-2`. We should prefix this.
- See a PHP warning after deleting all donations:
`( ! ) Warning: strtolower() expects parameter 1 to be string, array given in /Users/kevin/Sites/givesprintreview/wp-content/plugins/give/includes/admin/admin-pages.php on line 125`

## Expected Behavior

I expect to have these issues resolved before Give 2.1.

## Related

- #244

## Tasks

- [x] Only include one lock at the top of the Sequential Settings which unlocks all fields.
- [x] Rename `Starting Number` to `Next Donation Number`.
- [x] Allow a user to change the `Next Donation Number` to whatever they want and have the sequential ordering start at that number ( @ravinder-> working at my end)
- [x] Prevent warning when deleting all donations (described above).
- [x] Prefix the `post_name` with `give-` to avoid post name conflicts.
- [x] Add preview for sequential ordering on setting tab
