### ISSUE TITLE
fix(admin-tool): clarify donor export settings

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#2964]
## User Story

As an admin, I want to clearly understand what a "donor export" means so that I can retrieve the data I need.

## Current Behavior

I currently am confused when interpreting donor export data from all forms vs. a single form. `Donation Form` is particularly confusing since donors only appear once throughout the donor export.

## Expected Behavior

I expect to clearly understand what data I am exporting and viewing.

## Possible Solution

See https://github.com/WordImpress/Give/issues/2964#issuecomment-377463710

## Related

- https://github.com/WordImpress/Give/issues/2223
- https://github.com/WordImpress/Give/issues/2875

## Tasks

See https://github.com/WordImpress/Give/issues/2964#issuecomment-377463710

**Comment by raftaar1191** [comment]
Hey, @kevinwhoffman did not get you clearly. So just to confirm the above comment that you have made do you want to pre-select the **Donation Form fields** to **first Donation Form** in donor export section?



![image](https://user-images.githubusercontent.com/22215595/38127002-b53b240c-3411-11e8-9eda-436adfab7dba.png)

**Comment by kevinwhoffman** [comment]
**Slack Call Summary**

Participants: @raftaar1191 @kevinwhoffman
Topic: Clarify the changes to Donor export options
Result: We both agreed that `Donation Form` is a confusing column to include because each donor only appears once in the donor export (it is a unique list of donors). That means only the first `Donation Form` would be shown in the export, which is not clear. See below for changes.

![image](https://user-images.githubusercontent.com/1938671/38128382-586996f8-33c8-11e8-8744-f61c5abab9ed.png)

## Updated Tasks

- [ ] Update the field name and description as follows:
    - Setting Name: `Export Donors`
    - Description: `Download a CSV of donors. Column values reflect totals across all donation forms by default, or a single donation form if selected.`
- [ ] Remove the `Donation Form` checkbox control and CSV column.
- [ ] Rename `First Donation Date` to `Donor Created Date` in checkbox control and CSV column.
- [ ] Name the generated CSV file as follows:
    - If "All Forms" are selected, name it `give-export-donors-all-forms-03-30-2018.csv`
    - If one form is selected, name it `give-export-donors-{form-slug}-03-30-2018.csv`

**Comment by raftaar1191** [comment]
Now working as expected reopening this issue and fixing it
