### ISSUE TITLE
fix(admin-donations): sequential ordering should show # as default prefix to donation ids

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2977]
## User Story
As an admin, I want `#123` as a donation id when sequential ordering is enabled and (prefix & suffix) combined is empty so that the IDs throughout the plugin looks consistent.

## Current Behavior
I currently can see the donation id as `857` when sequential ordering is enabled with prefix and suffix empty. However, the Donor ID and Donation Form ID on Donation Detail page has `#<some number>` format. 

## Expected Behavior
I expect to have the donation id as `#857` when sequential ordering is enabled with empty prefix and suffix to make the donation id look consistent throughout the plugin.

## Steps to Reproduce
1. Install Give `2.1`
2. Go to `Settings > General > Sequential Ordering`
3. Apply Settings as per screenshot (1)

## Visuals
**Screenshot (1) - I have used default settings with just sequential ordering enabled**
![image](https://user-images.githubusercontent.com/1852711/38185458-c4f868d0-366b-11e8-8df1-256125f0ccc5.png)

**Screenshot (2) - No # symbol before donation id**
![image](https://user-images.githubusercontent.com/1852711/38185513-0b7854d2-366c-11e8-828e-16a8fadf3cd0.png)

**Screenshot (3) - # symbol on donation detail page which makes the look and feel inconsistent**
![image](https://user-images.githubusercontent.com/1852711/38185539-3748360e-366c-11e8-94f3-054d32837f03.png)

## Tasks
- [ ] Investigate the areas which are affected.
- [ ] Add `#` as a default prefix to all the applicable screens.
- [ ] Testing

## Environment

<details>
    <summary>WordPress System Info</summary>
    ### WordPress Environment ###

Home URL: http://give.test
Site URL: http://give.test
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.test
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.2.0
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.1.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access❌Renewal Receipt Email❌Subscription Cancelled Email
Upgraded From: 2.0.3
Test Mode: Enabled
Currency Code: EUR
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give.test/donation-confirmation/
Failure Page: http://give.test/donation-failed/
Donation History Page: http://give.test/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, PayPal Standard, Stripe + Plaid
Default Payment Gateway: Stripe + Plaid
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - Form Field Manager: ❌ Unlicensed – by WordImpress – 1.2.8
Give - PayPal Pro Gateway: ❌ Unlicensed – by WordImpress – 1.1.4
Give - Recurring Donations: ❌ Unlicensed – by WordImpress – 1.5.7
Give - Stripe Gateway: ❌ Unlicensed – by WordImpress – 1.5.2

### Other Active Plugins ###

Gutenberg: by Gutenberg Team – 2.4.0
Query Monitor: by John Blackbourn – 2.17.0

### Inactive Plugins ###

Give - 2Checkout Gateway: by WordImpress – 1.1
Give - Authorize.net Gateway: by WordImpress – 1.3
Give - Currency Switcher: by WordImpress – 1.0.2
Give - eWay: by WordImpress – 1.0
Give - PayFast Payment Gateway: by WordImpress – 1.0
Give - PDF Receipts: by WordImpress – 2.2.2
Give - Square: by WordImpress – 1.0
Loco Translate: by Tim Whitlock – 2.1.0
Polylang: by Frédéric Demarle – 2.3.1
Snippet Library: by  – 1.0
W3 Total Cache: by Frederick Townes – 0.9.6
WooCommerce: by Automattic – 3.3.3
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.5.2
WooCommerce Stripe Gateway: by WooCommerce – 4.0.7

### Active MU Plugins ###

Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X </li>
        <li>Version: 10.12.6</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Safari | IE | Edge</li>
        <li>Version: Latest</li>
    </ul>
</details>

**Comment by ravinderk** [comment]
@mehul0810 We can remove `#` from donation detail page also.
Check this: https://github.com/WordImpress/Give/pull/2954#issuecomment-377099997

@kevinwhoffman do you want me to remove `#` from donation detail page?

**Comment by kevinwhoffman** [comment]
@ravinderk Go ahead and remove `#` from the donation details page for consistency.

**Comment by ravinderk** [comment]
@kevinwhoffman What is your view on donor listing and donor detail page:


![image](https://user-images.githubusercontent.com/1784821/38228076-1bcd7980-371f-11e8-8bf0-76a5715fee90.png)

![image](https://user-images.githubusercontent.com/1784821/38228079-274bed6e-371f-11e8-9b16-cbe8a5064075.png)

**Comment by kevinwhoffman** [comment]
## Donor Overview

- [ ] Remove `#` from `Name` column

![image](https://user-images.githubusercontent.com/1938671/38229366-8623c5bc-36d6-11e8-8b08-0c5b99e77977.png)

## Donor Detail (Unregistered)

- [ ] Remove `#` from page title and donor name
- [ ] Add `Donor ID` row as shown.
- [ ] Change `None` to `Unregistered` as the default value for `User ID`.

![image](https://user-images.githubusercontent.com/1938671/38229527-2668e55c-36d7-11e8-9599-e03277bcb5ac.png)

## Donor Detail (Registered)

Here is a registered user for reference.

![image](https://user-images.githubusercontent.com/1938671/38229311-4823bdda-36d6-11e8-8620-6f253e22fd9f.png)
