### ISSUE TITLE
fix(admin-shortcode): Total goal attribute should be required field for [give_totals]

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#3060]
## User Story
As an admin, I want Total Goal attribute of [give_totals] shortcode should be required so that I can see a positive goal and progress bar visible on the front end.

## Current Behavior
I currently can't see the progress bar and can see goal amount to be `$0` when the total_goal attribute is not provided with [give_totals] shortcode.

## Expected Behavior
I expect to have the total goal attribute to be required field for [give_totals] shortcode.

## Visuals
**Admin end - Popup of [give_totals] shortcode**
![image](https://user-images.githubusercontent.com/1852711/38925098-3e60676a-431c-11e8-809b-7f194a053eb1.png)

**Frontend - When total goal attribute is not provided in [give_totals] shortcode.**
![image](https://user-images.githubusercontent.com/1852711/38925370-0ed60e2c-431d-11e8-8bd5-1202f5f784b9.png)

**Frontend - When total goal attribute is provided in [give_totals] shortcode**
![image](https://user-images.githubusercontent.com/1852711/38925309-dc971528-431c-11e8-9267-ae70dc64a768.png)

## Related
- https://github.com/WordImpress/Give/issues/1472

## Tasks
- [ ] Make the total goal attribute required field for [give_totals] shortcode.
- [ ] Testing

**Comment by ravinderk** [comment]
@raftaar1191 create pr for this issue again and take `release/2.1.4` as parent

**Comment by raftaar1191** [comment]
Sure @ravinderk here is the new PR link for the issues https://github.com/WordImpress/Give/pull/3284/

**Comment by mehul0810** [comment]
I'm re-opening this issue as we are showing validation error notice. But, the `warning notice` is shown instead of `error notice`.

## Tasks to implement
- [ ] Change `Warning` notice to `Error` notice
- [ ] After clicking `OK` on notice, the validated field should get focus.

**Comment by raftaar1191** [comment]
@mehul0810 @ravinderk 

As discussed with @ravinderk on call, we will be going to take care of point number 2 ` After clicking OK on notice, the validated field should get focus.` in https://github.com/WordImpress/Give/issues/3060#issuecomment-394301653 by @mehul0810  in the following [issues ](https://github.com/WordImpress/Give/issues/3320)
