### ISSUE TITLE
fix(admin-donation): form earnings does not update when change donation amount

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#3085]
## User Story
As an `admin`, I want form earning update when donation amount update so that I do not have to use data tools to check latest stats.

## Current Behavior
Form earning is not changing when updating donation amount.

## Possible Solution
Run this condition when donation amount update: https://github.com/WordImpress/Give/blob/release/2.1/includes/payments/class-give-payment.php#L970

## Tasks
- [ ] Update logic to update form earning when donation amount update.

## Tests
- [ ] After updating donation amount, review following:
   - [ ] Review form earnings
   - [ ] Review total donor donated the amount
- [ ] Test with recurring renewal donation payment

**Comment by ravinderk** [comment]
In favor of https://github.com/WordImpress/Give/pull/3389#issuecomment-399090050

**Comment by raftaar1191** [comment]
@ravinderk I am able to reproduce this issue. I am adding a video to show you on how we can reproduce this issues 


Video Link: https://screencast-o-matic.com/watch/cF13fPFDhV

**Comment by raftaar1191** [comment]
Slack Call Summary

Participants: @raftaar1191, @ravinderk
Topic: Reopening this issues 
Result: Reopening this issues as we can reproduce this issues over the call and also @ravinderk showed to me some of give function which already does increment and decrement for Form total earning so we do not need to make a new function for that. So closing the PR https://github.com/WordImpress/Give/pull/3389 and created a new one https://github.com/WordImpress/Give/pull/3396 for the above issues
