### ISSUE TITLE
perf(query): reduce code/query for getting information about activation banner.

### ISSUE THREAD

**Issue by emgk** [WordImpress/Give#3130]
## User Story
As an `Admin`, I want `reduce the SQL queries of the Add-on banner on each page` so that `page can be load faster`. 

## Current Behavior
Currently, the query is calling multiple time on each page.

## Expected Behavior
I expect to run the queries only once on load.

## Tasks
- [x] Load banner related logic only on plugin listing page.
- [x] Create the new helper function to store SQL result globally.
- [x] Create a new method to get the option key.
