### ISSUE TITLE
fix(form): Make dropdown display inside the modal with Button Mode

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#3215]
## User Story

As a Give user I want to use Button mode and have multi-levels displayed as a dropdown.

## Current Behavior
Currently, the dropdown appears ABOVE the button in button mode. See sample here:

## Expected Behavior
I expect the dropdown to appear inside the modal.

## Steps to Reproduce
1. Create a form with multi-levels and set it to Button Only mode.
2. View it on the frontend and confirm that the dropdown appears ABOVE the button

## Related
- Reported here: https://wordpress.org/support/topic/setting-form-display-to-button-only-displays-a-dropdown-above-button/
- See live example here: https://www.mattcromwell.com/give-test/

## Tasks

- [ ] Ensure dropdown appears inside the modal in button mode
- [ ] double-check other modes as well
- [ ] Test with the Give Widget as well
- [ ] Test with a form that is not set to button mode by default, but use the shortcode builder to change the display mode and ensure the dropdown is STILL inside the modal.
