### ISSUE TITLE
Typos on Set-up guide

### ISSUE THREAD

**Issue by telizarose** [WordImpress/Give#3230]
## User Story

Noticed some typos in the "Welcome Screen" > "Getting Started" section.

## Current Behavior

It says "it's" and periods outside of quotations "example".

## Expected Behavior

It should say "its" and periods should be inside quotes "example." 

## Visuals

![image](https://user-images.githubusercontent.com/38927530/40147905-523b1252-5920-11e8-903a-10c99f53a029.png)

## Tasks

- [ ] Change "it's" to its.
- [ ] Move first period inside quotation. 
- [ ] Move second period inside quotation.

**Comment by DevinWalker** [comment]
Thanks - resolved 3ffa181fe03d27c3f89676efdba4aaa6a1febe3b
