### ISSUE TITLE
fix(admin-form): Ensure custom logo appears in email Preview when properly configured

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#3330]
## User Story

As a `Give Admin`, I want to have an actual preview of my custom emails when I chose to customize the email of a specific form. Specifically, if I choose a different logo for one form, I expect that when I use that form's "Preview Email" button that I'll see that custom logo there, not the logo set in the global settings. 

## Current Behavior
Currently, the general settings logo is the only one that appears with the Preview Email feature on individual forms even when a custom logo has been set correctly.

## Expected Behavior
I expect to be able to set the custom logo, click on the Preview Email button, and see the custom logo appear correctly in that preview.

## Steps to Reproduce
1. Ensure that in "Donations > Settings > Emails" that you've set a logo image
2. Go to a specific form, then go to "Email Notifications", set it to "Customize"
3. For the "Logo" option, select an image that is different from the global settings. Like so:
![image](https://user-images.githubusercontent.com/930724/41054389-193ec634-6973-11e8-9b67-0943a2be8055.png)
4. Go to the "New Donation" tab, select "Customize" and Save the form
5. Go to the "New Donation" tab again and scroll down to the "Preview Email" button. You will see the global settings logo in the preview instead of the custom logo. Even if you select a donation that is made from that form, it's still the global settings logo. See here:
![image](https://user-images.githubusercontent.com/930724/41054498-66385dec-6973-11e8-8066-e35f4fc0f3aa.png)

*NOTE:* The customized logo is SENT correctly. This only affects the Preview, not the actual final email. But this creates a confusing user experience.

## Related
- HS Ticket: https://secure.helpscout.net/conversation/591178219/19363/?folderId=672201

## Tasks

- [ ] Ensure that the Preview Email shows the custom logo if it is selected.
- [ ] After that is implemented, Ensure that if the Email Notifications is NOT set to customize, that the Preview Email correctly shows the global settings logo.
- [ ] Ensure that both those options above work as intended when the email is actually sent as well.
