### ISSUE TITLE
feat(shortcode): Add Company attribute to give_receipt shortcode

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#3361]
## User Story

As a `Give Admin` I want to be able to display the Company field on the Donation Receipt page.

## Current Behavior
Currently, the Company Name is not added by default to the receipt, and there's no option to add it without code.

## Expected Behavior
I expect that the Company field would be included in the output of the `give_receipt` shortcode by default, and that I'd have the option in the Shortcode Builder to exclude it optionally:

![image](https://user-images.githubusercontent.com/930724/41382252-3a4492e8-6f20-11e8-8272-1f6f0dd3c48f.png)

## Related

- HS Ticket: https://secure.helpscout.net/conversation/600810076/20156?folderId=672194

## Tasks
- [ ] Ensure the company field is output (if present) in the output of the Donation Receipt by default
- [ ] Add the Company field as an option in the Shortcode Builder with "Include" as the default value, with an additional option to "Exclude" it.
- [ ] Ensure that the output of the donation receipt respects the new shortcode attribute when it's set to exclude the company field.

**Comment by mathetos** [comment]
*UPDATE:*
I do see that the code to pass the value is in the shortcode, but it has to be passed as `company_name="true"` in order to display, and as shown above, that's not discoverable in the builder. So the only task is to have it output by default (if present) and show in the builder).

**Comment by raftaar1191** [comment]
@ravinderk Here is the point that needs to be cover but the first two-point is not done as expected. The third point is working fine  

- [ ] Ensure the company field is output (if present) in the output of the Donation Receipt by default
- [ ] Add the Company field as an option in the Shortcode Builder with "Include" as the default value, with an additional option to "Exclude" it.
- [x] Ensure that the output of the donation receipt respects the new shortcode attribute when it's set to exclude the company field.

**Comment by ravinderk** [comment]
@mathetos @raftaar1191 

We can not show company name by default because  Shortcode builder do not generate attribute value for default value and it will be difficult to add backward compatibility for existing receipt shortcode. .

**Comment by mathetos** [comment]
@ravinderk I think I understand. Essentially, we currently only have a global setting for the Company option, not a per-form setting. So your PR essentially just ensures that the Company field is output in the Donation Receipt by default, no changes necessary to the shortcode at all. 

But to be clear, I was referring to the Shortcode Builder for the `give_receipt` shortcode, not the `give_form` shortcode. So we're not talking about per-form functionality when it comes to the Builder. Instead, the Builder is used for customizing the `give_receipt` shortcode. This would respect the global setting just fine. I'm simply saying that because we have the option in the shortcode, we should expose that in the Builder.

Does that make sense?

**Comment by ravinderk** [comment]
@mathetos We have per form company field setting:

![image](https://user-images.githubusercontent.com/1784821/41427795-ac8e1dc8-7025-11e8-91f3-93f9666ab7b9.png)

**Comment by ravinderk** [comment]
> Slack Chat Summary
> 
> Participants: Matt Ravinder
> Topic: Shortcode Builder
> Result:There was confusion about what Ravinder's PR actually did. It turns out it does exactly what Matt was hoping for and this should resolve the user issue completely.
