### ISSUE TITLE
fix(compat): resolve conflict with True Mag Theme

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#3381]
## User Story

As a `site admin`, I want `to be able to use the true Mag theme alongside give` so that `my donors can give to my cause`.

I expect updates to Give to not break things on my forms. 

## Current Behavior
I currently can't use Give at all on the True Mag theme from Themeforest.

Here's an admin defined recurring multilevel form:
![screen shot 2018-06-18 at 4 39 20 pm](https://user-images.githubusercontent.com/9629102/41560841-52460558-7316-11e8-9938-85a633bf5224.png)

## Expected Behavior

I expect the theme to work with Give.

## Steps to Reproduce
1. Install and activate the True Mag theme (zip provided in Slack as a thread on this issue)
2. View any form.
3. Cry a little. 

## Related
- https://secure.helpscout.net/conversation/600429672/20112?folderId=848135

## Tasks

- [ ] confirm functionality with multilevel forms
- [ ] confirm functionality with modal forms
- [ ] confirm functionality with reveal forms
- [ ] confirm functionality with button forms
- [ ] confirm functionality with shortcode embedded on a new page forms
- [ ] confirm functionality with goal forms

**Comment by kevinwhoffman** [comment]
@Sidsector9 Please install the True Mag theme that Ben has provided in Slack. Complete the tasks he has outlined and take steps to fix the CSS. Do NOT add the CSS to Give. Instead create a snippet and add it to https://github.com/WordImpress/Give-Snippet-Library/tree/master/theme-compatibility.

**Comment by kevinwhoffman** [comment]
@Benunc @mathetos Sid put 4 hours into troubleshooting this theme and concluded that Give is completely broken in this theme with no obvious cause. Letting you know so we can communicate it to customer.

**Comment by mathetos** [comment]
I'll dig into it myself later this week. There must be a cause and a workaround. But I won't spend more then one hour.

**Comment by mathetos** [comment]
I found the issue, the theme was preventing Give from accessing the post_meta because of this function:

```
if(!function_exists('cactus_hook_get_meta')){
	function cactus_hook_get_meta($metadata, $object_id, $meta_key, $single) {
		$fieldtitle="_jwppp-video-url-1";
		if($meta_key=$fieldtitle && isset($meta_key)) {
			//use $wpdb to get the value
			global $wpdb;
			$value = $wpdb->get_var( $wpdb->prepare( 
				"
					SELECT meta_value 
					FROM $wpdb->postmeta 
					WHERE post_id = %s 
					AND  meta_key = %s
				",
				$object_id,
				'tm_video_url'
			));
			if($value==''){
				$value = $wpdb->get_var( $wpdb->prepare( 
					"
						SELECT meta_value 
						FROM $wpdb->postmeta 
						WHERE post_id = %s
						AND  meta_key = %s
					",
					$object_id,
					'tm_video_file'
				));
			}
			//do whatever with $value
	
			return $value;
		}
	}
}
if(!is_admin()){
	add_filter('get_post_metadata', 'cactus_hook_get_meta', 10, 4);
}
```

Disabling the filter that called that function fixes the problem completely and doesn't seem to cause issues with other parts of the theme. I advised the user to contact the theme author about the problem and seeking further support from them.

Since this is a PHP issue, not a simple incompatibility that a snippet would fix, I'll close this issue for now.
