### ISSUE TITLE
fix(emails): remove Give Shortcode button from the editor for creating emails

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#3422]
## User Story

As a `give admin`, I don't want `options to add Give Shortcodes to emails` because `shortcodes don't work in emails`.

Currently, when I navigate to `Donations > Settings > Emails` and select one of the emails to edit, there is an option to add give shortcodes to the emails.

If I am new to Give, I might think those are appropriate spots for Give shortcodes. 

## Current Behavior
I currently see the option for adding shortcodes to emails.

## Expected Behavior
I expect to not be given the option to add shortcodes where they won't work. 

## Steps to Reproduce
1. Latest Master
2. Navigate to Donations > Settings > Emails (tab) and select an email to edit
3. There is a shortcode button there. 

## Visuals

<img width="648" alt="screen shot 2018-06-29 at 6 43 40 am" src="https://user-images.githubusercontent.com/9629102/42088542-d2aac162-7b67-11e8-97ba-00a1ae802c4b.png">

## Related
- https://secure.helpscout.net/conversation/609185954/20663?folderId=848135

## Tasks

- [ ] remove the button from the visual tinymce editor on each email
- [ ] remove the button from the text tinymce editor
- [ ] confirm that the solution is extensible: emails added by add-ons also do not get the shortcode button

**Comment by ravinderk** [comment]
@Benunc @DevinWalker I think we should remove `Give Shortcodes` button from all setting pages because it will add to all wp editor, not just email.

![image](https://user-images.githubusercontent.com/1784821/42430125-f38cef5e-835a-11e8-8998-a6f78934080b.png)

**Note:** We can use `give_shortcode_button_condition` filter to show `Give Shortcodes` on custom pages

**Comment by ravinderk** [comment]
Closing in favor of https://github.com/WordImpress/Give/commit/cd544ddf8b6f6603429a372c0e7f217b7394b9be
