### ISSUE TITLE
fix(compat): move `babel-polyfill` to Give core

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#3433]
## User Story

As a developer, I want ES6 polyfills included in Give core so that they don't have to be enqueued multiple times in each add-on that requires them, which can result in conflicts like https://github.com/WordImpress/Give-Donation-Upsells-WooCommerce/issues/40.

Currently the WooCommerce and Stripe add-ons are incompatible so we need to take action immediately.

## Possible Solution

@mehul0810 and I suggest enqueuing `babel-polyfill` with its own unique handle in Give core, while removing the polyfill from Stripe and WC add-ons.

## Related

- https://github.com/WordImpress/Give-Donation-Upsells-WooCommerce/issues/20
- https://github.com/WordImpress/Give-Donation-Upsells-WooCommerce/issues/40
- https://github.com/WordImpress/Give-Stripe/issues/250

## Tasks

- [x] Enqueue `babel-polyfill` in Give core.
- [x] Remove `babel-polyfill` from Stripe add-on.
- [x] Remove `babel-polyfill` from WooCommerce add-on.
- [ ] Release patches for Give core, Stripe, and WC simultaneously.

**Comment by samsmith89** [comment]
When running NPM RUN DEV this throws an error because it isn't present. Is that intended behavior?
![screen shot 2018-07-10 at 8 32 14 am](https://user-images.githubusercontent.com/20672471/42510079-c858a992-841b-11e8-87d8-b081e4b6220c.png)

**Comment by ravinderk** [comment]
@samsmith89 I think this issue is with your plugin path. Rename `Local Sites` to `Local-Sites`

**Comment by raftaar1191** [comment]
As this issues being fixed in Give Core version `2.1.7` so removing it from 2.2.0 release
