### ISSUE TITLE
fix(composer): Include PHP libraries using composer

### ISSUE THREAD

**Issue by Sidsector9** [WordImpress/Give#3482]
## User Story
As a `developer`, I want Give Core to include libraries using Composer instead of manually adding it into the `libraries` folder so that there are no chances of plugin conflicts.

Composer has it's own way to handle namespaces even for libraries which do not have their own namespaces. The motive for creating this issue was the [issue](https://github.com/WordImpress/Give-PDF-Receipts/issues/153) that occurred in PDF-Receipts, where the plugin [WP DSGVO Tools](https://wordpress.org/plugins/shapepress-dsgvo/) uses the TCPDF library, same as Give. Using `if ( ! class_exists( 'CLASS_NAME' ) )` is tedious as the errors are in succession due to multiple classes being repeated. This solution is not feasible.

## Current Behavior
Existence of the current TCPDF class and other classes inside `include/libraries/tcpdf` causes fatal error.

## Expected Behavior
I expect that no fatal error occurs due to multiple declaration of the same classes.

## Possible Solution
1. Delete the folder `tcpdf` from within `includes/libraries/`
2. Run `composer require tecnickcom/tcpdf`
3. Add `require_once GIVE_PLUGIN_DIR . 'vendor/autoload.php';` somewhere in the Give Core

## Tasks

- [x] Use composer to include the TCPDF library and others if necessary and possible.

**Comment by ravinderk** [comment]
@Sidsector9 please push all changes in `https://github.com/WordImpress/Give/pull/3496`. This needs to test in depth

**Comment by Sidsector9** [comment]
|          | Version | Size   |
|----------|---------|--------|
| Give's TCPDF     | 6.2.13  | 8.6MB  |
| Composer's TCPDF | 6.2.17 (latest)  | 32.3MB |

**3/98** repositories under WordImpress depend on the TCPDF library, they are:
1. Give-Gift-Aid
2. Give-PDF-Receipts
3. Give-Tributes

CC: @DevinWalker @ravinderk  @kevinwhoffman

**Comment by DevinWalker** [comment]
@Sidsector9 can we via composer only include the TCPDF files necessary as described in that StackOverflow article? Otherwise, each time we use composer update then we'll have to remove those files manually, which can be prone to errors and tedious.

**Comment by Sidsector9** [comment]
@DevinWalker , I don't think the client can decide to include specific dependencies. However, we can write a task for production to delete unnecessary files and folder inside TCPDF. What do you say? 

CC: @ravinderk

**Comment by DevinWalker** [comment]
@Sidsector9 the only issue I see with that is if TCPDF changes directory structures and we run `npm run production` it could cause issues if we don't catch it.

**Comment by Sidsector9** [comment]
@DevinWalker  I see your point, so I researched and analysed the previous versions: 6.2.10 - 6.2.17, the folder structure remains same. And in our case, the folder of focus which takes most of the space is the fonts folder, we can leave the other files as it is as they don't affect the overall size significantly. In case if the deletion task fails to delete files which are not present, we will be informed while running the task.

**Comment by DevinWalker** [comment]
@Sidsector9 please proceed with this and updating the dependent add-ons with the 

## Uses TCPDF via Composer:

- [ ] Give-Gift-Aid
- [ ] Give-PDF-Receipts
- [ ] Give-Tributes

### Additional Questions

Which of the remaining libraries in the `includes/libraries` directory can we move over to composer?

![2018-07-31_14-46-57](https://user-images.githubusercontent.com/1571635/43489070-958e5258-94d0-11e8-985b-f771949358ae.png)

I think most of these are used by core, but can you review which may be used by add-ons?

**Comment by Sidsector9** [comment]
Sure @DevinWalker, once I take care of the above 3 addons, I'll research on the other libraries that can be included via Composer in Give Core.
