### ISSUE TITLE
fix(form-settings): Ensure prefixes works as described

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#3488]
## User Story

As a `Give Admin` I want to be able to use the new Give 2.2 prefixes feature and for it to behave as expected based on the settings description.

Currently the description suggests several prefixes that don't seem to be available and there doesn't seem to be a way to add them either. 

## Current Behavior

I currently see the following description in the form settings "Name Title Prefix" option:

> Do you want to add a name title prefix dropdown field before the donor's first name field? This will display a dropdown with options such as Mrs, Miss, Ms, Sir, and Dr for donor to choose from.

But the only options available are `Mr | Mrs | Ms`
![image](https://user-images.githubusercontent.com/930724/42789915-c6baee28-891c-11e8-8bd0-fd3d33cb57a9.png)

## Expected Behavior

I expect that inline documentation matches with the actual options available.

## Possible Solution
There are two options to resolve this:

1. Add the ability to add custom prefixes
2. Update the form display settings description to be more accurate. 

If choosing option 2, here's my suggested wording:

`Enable a prefix to appear before the donor name. Options are "Mr., Mrs., and Ms."

Additionally, there should always me a period (.) after each of those abbreviations. 

## Tasks

- [ ] Either fix the form setting description; or add the ability to add custom prefixes
- [ ] Ensure a period is placed after each existing prefix option
- [ ] Ensure localization of this description will still be rendered correctly. 
- [ ] If adding custom prefixes, ensure they render in the form settings correctly, and are output on the form correctly, and are passed to the donation meta and donor emails correctly

## Environment
[Give branch 2.2](https://github.com/WordImpress/Give/tree/release/2.2)

**Comment by ravinderk** [comment]
@mathetos We already have the functionality to add custom title prefixes.


![image](https://user-images.githubusercontent.com/1784821/42815506-2e8646ba-89e5-11e8-9fee-30117ffb33bd.png)

**Comment by ravinderk** [comment]
@mathetos Can you provide field description?
To be clear we can add custom title prefix, we just have to press enter when we did not find it in options.

**Comment by mathetos** [comment]
@ravinderk @raftaar1191 I tested again after pulling down the latest 2.2 branch and all works exactly as expected now. 

The only minor issue remaining is that the default options need to have a period: `Mr. | Mrs. | Ms.`

Once that's done we can close this out. Thanks!

**Comment by mehul0810** [comment]
## Slack Call Summary
Participants: @ravinderk @mehul0810
Topic: Discussion about the change requested to add period at the end of the title prefix by default
Result: I'll not add period at the end of the title prefix automatically even if the title prefix selected in admin is not having a period in the end. Only the default title prefixes ( i.e. `Mr.`, `Mrs.`, and `Ms.` ) will have a period in the end.

**Comment by raftaar1191** [comment]
Reopen this issue to cover up the following poting 

https://github.com/WordImpress/Give/pull/3501#issuecomment-405831175
