### ISSUE TITLE
feat(admin-tool): add option to delete only donation data

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#3583]
## User Story

As a `give admin`, I want `to be able to delete all donation data without deleting forms and other settings` so that `I can duplicate a site or start fresh without any donations`.

## Current Behavior
I currently have to manually delete all data from the Donations > DOnations page by selecting all and deleting, and that only gets 30 donations at a time. 

## Expected Behavior
I expect to be able to delete all donations and start fresh.

## Related
- https://secure.helpscout.net/conversation/621263375/21514?folderId=848135 (Errors created many duplicate donations in the DB, and they wanted to delete and start fresh)

## Tasks
- [x] add delete functionality for donations only.
- [x] add in the ability to delete donations before a certain date.
- [ ] add the ability to extend this functionality in recurring to also delete subscriptions

**Comment by Sidsector9** [comment]
@ravinderk Should the 3rd task of this issue be a part of Recurring Addon entirely or should we include it in Give Core by checking if Recurring is active or not?

**Comment by ravinderk** [comment]
@Sidsector9 create a new issue to third todo on recurring addon repo and add reference too.
