### ISSUE TITLE
refactor(comment): create custom comment table

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#3627]
## User Story
Give uses WordPress comment functionality. In Give, the comment is mostly used as a note for record activity of donor or donation and donor comment (if enabled): Few plugins start flagging these comment a spam, so in some case, donation process but donor does not notify successfully that means they land on error page instead of donation receipt page.

To prevent this issue we will create a custom comment table to store donation and donor activity.

# ToDo
- [x] Custom Table
   - [x] Create custom table
   - [x] Add helper functions
   - [ ] Add comment query caching ( not improtant, becuase comment query is not expensing and for now only query for comment on donation detail page )
- [x] Add DB upgrade 
- [x] Review backward compatibility
- [x] Testing
   - [x] Review DB upgrade
   - [x] Donor wall shortcode
   - [x] GDPR plugin (after db upgrade)
   - [x] Mojo Market place plugin (after db upgrade)
   - [x] Addons 
        - [x] Manual Donation
        - [x] Stripe
        - [x] Paypal Pro
        - [x] Recurring
         Note: most payment gateways uses `give_insert_payment_note helper` function.
- [ ] Write developer blog post
