### ISSUE TITLE
epic(jest): add test cases for front-end UI testing

### ISSUE THREAD

**Issue by Sidsector9** [WordImpress/Give#3629]
## User Story
As a `developer`, I want to make sure that all important areas of front-end is tested so that bug rates are low.

## Tasks

- [x] Test Set Donation UI and Donation Receipt Page
- [x] Test Multi Donation UI and Donation Receipt Page
- [x] Test all payment methods that come with Give Core
- [x] Test Custom Price input field and Donation Receipt Page
- [x] Test Donation Comment input field
- [x] Test Anonymous Donation checkbox field
- [x] Test name prefix field and dropdown values
- [x] Test Offline Instructions
- [x] Test Form Grid
- [x] Test Donor Wall
- [x] Test all 10 shortcodes

**Comment by Sidsector9** [comment]
## Progress
For multiple test cases, I've broken down the test cases into multiple files.

### Problems faced
Jest by default runs tests parallelly, but since we're using Puppeteer along with Jest, it is trying to test several pages all at once which causes timeout issues, due to which tests failed.

### Solution
After some research, I came across a parameter `--runInBand`, so running `jest -c --runInBand` makes it run tests sequentially. This has fixed the problem.

**Comment by Sidsector9** [comment]
### Progress
This is a quick video about the tests done until now:
https://www.useloom.com/share/c6a6bb496e1943f7ab70821a52cecca2

CC: @ravinderk @DevinWalker
