### ISSUE TITLE
feat(admin-plugins): add a popup survey upon plugin deactivation

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#648]
We've had a couple very negative reviews about the uninstall process leaving data behind after Give is deleted. Here's my suggestion to help those users:

We trigger a popup when the Deactivate link is clicked on the Give plugin.

That popup would say the following:

> **Deleting Give? Read this First.**
> By default the custom roles, Give options, and database entries are not deleted when you delete Give. If you are deleting Give completely from your website and want those items removed as well, first go to "Donations > Settings" then the "Advanced Options" tab and check the setting that says "Remove All Data on uninstall". 
> 
> **Do you want to go ahead with Deactivation?**
> [Yes]    [Cancel Deactivation]

### Tasks
- [x] Add the popup survey form on deactivation using Give Modal API
- [x] Create API endpoint (a separate addon) which will receive survey data and store data in the database.
- [x] Test the whole feature.

**Comment by joeguilmette** [comment]
Why not include the options in the popup? You can keep them in both places, or just have them in the deactivate popup. But to me, the popup seems to be the best place to present this decision to the user.

**Comment by DevinWalker** [comment]
I'm not so sure about the message here. I'd rather our deactivation popup be more like how freemius handles the deactivation WITH the ability to specify deleting custom data.

**Freemius' popup:**

![screen shot 2016-07-18 at 12 11 14 pm](https://cloud.githubusercontent.com/assets/1571635/16927152/f6394304-4ce0-11e6-9683-7389640cb6e1.png)

---

**My vision:**

> Deactivating Give

If you have a moment, please let us know why you are deactivating Give. All submissions are anonymous and we only use this feedback to improve the plugin.

- I no longer need the plugin
- I found a better plugin
   - What is the plugin's name?
- I only needed the plugin for a short period
- The plugin broke my site
  - We're sorry to hear that and offer free support of WordPress.org (link). Can you describe the issue?
- The plugin suddenly stopped working
  - We're sorry to hear that and offer free support of WordPress.org (link). Can you describe the issue?
- Other
   - Please describe why you're deactivating Give

(checkbox) Would you like to delete all Give data? 
*By default the custom roles, Give options, and database entries are not deleted when you delete Give. If you are deleting Give completely from your website and want those items removed as well*

![deactivation-popup](https://cloud.githubusercontent.com/assets/1571635/16927977/23905e4c-4ce5-11e6-887d-2138a8ccb98c.png)

**Comment by mathetos** [comment]
I love it. VERY informative, and I think users will appreciate the information. Let's do it!

**Comment by DevinWalker** [comment]
@mathetos how about the form submits to a Google spreadsheet?

**Comment by mathetos** [comment]
@DevinWalker Really don't think that's a long-term solution. Would prefer to store it properly in a database of some sort so it's portable and we can report the data any way we want. Also, I haven't been happy with the reliability of pushing data to GOogle spreadsheets.

**Comment by DevinWalker** [comment]
@mathetos I agree, a spreadsheet seems janky at best. Let's plan on submitting to a custom endpoint on our website where to store the data in our db.

**Comment by DevinWalker** [comment]
Take a look how @vovafeldman updated their deactivation popup:

1. Randomized the order of the choices to improve data accuracy
2. Allow for anonymous entries
3. When the user choose "I didn't understand how it works", it shows a contextual "Contact Support" button with a direct link to a contact us page.

https://github.com/Freemius/wordpress-sdk/releases/tag/1.2.1

Very neat stuff...

**Comment by Sidsector9** [comment]
This is the progress so far - 

![survey](https://snag.gy/mARxow.jpg)

**Comment by DevinWalker** [comment]
It's looking good but not exactly like the concept above. For instance, the "G" icon is larger and the width of the modal is too slim. Can you match it up a little better @Sidsector9 ?

**Comment by Sidsector9** [comment]
This is the survey form after feedback - 

### Survey Form
![surveyform](https://snag.gy/QA2G1g.jpg)

### Dashboard (WIP)
![surveystats](https://snag.gy/cfJS0u.jpg)

**Comment by DevinWalker** [comment]
Looking good @Sidsector9

**Comment by kevinwhoffman** [comment]
@Sidsector9 @DevinWalker  Nice progress. Are we still planning to provide the checkbox to delete Give data on deactivation? I think that was the original reason for the issue and want to make sure it doesn't get lost in the other feedback functionality.

**Comment by Sidsector9** [comment]
@kevinwhoffman Yes we are going to provide the checkbox. That is the last part of the implementation of this whole feature.

**Comment by menathor** [comment]
Hi guys! Sorry to comment on an old thread. I've just added a deactivation form to my new plugin and was searching for an example stats dashboard I could check out. Yours looks great- do you have it available on github?

**Comment by DevinWalker** [comment]
@menathor yes we do I can add you to the repo now

**Comment by menathor** [comment]
Awesome, thanks so much!

**Comment by jcvangent** [comment]
@binaryfire could you maybe add me to that repo as well? Looks interesting!

**Comment by jcvangent** [comment]
Oh wait, @DevinWalker you're the person to do this, could you maybe add me to the repo as well? Would love to see how you folks build that dashboard!
