### ISSUE TITLE
Improve Strings and Links to Docs

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#889]
We have several overlapping projects going on currently that achieve similar but distinct goals. Coordinating those all in this one ticket will help manage better.
## GOAL

To make our plugin more efficient in it's use of language strings, by consolidating them, and shortening them, and when shortened linking to relevant online docs for full descriptions.
## STRATEGY
- [x] Consolidate similar strings so they only have to be translated once ( #879 assigned to @ramiy  )
- [x] Shorten Descriptions ( #876 assigned to @mathetos )
- [x] Convert all Docs links to Shortened Links (#890 assigned to @mathetos)
- [x] Add new links to Docs whenever relevant

**Comment by DevinWalker** [comment]
While it would be nice to get this into 1.7 I think it's more of an ongoing task. I'm bumping it off the 1.7 milestone but if we could get the bulk majority done by then that would be great!
