### ISSUE TITLE
Deprecate usage of CMB2 in favor of our own settings & metabox fields

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#991]
**Summary:** CMB2 has proved to be a great for Give as an MVP starting point. Now we're being really held back with what we want to do with our settings section in #668 and our donation form creation screen here #281. 

**Approach:** Let's first 

- [x] Decide on a backwards compatible approach - whether we should use WooCommerce's approach or move forward with the EDD approach as we have already here: https://github.com/WordImpress/Give/blob/master/includes/class-give-html-elements.php it needs to be able to take the `cmb2` field array we pass and create the same fields
- [x] Develop new settings section with sub-tabs per section *without* using CMB2
- [x] Design new donation form creation UI re: #281
- [x] Develop new donation form creation UI re: #281
- [x] New tools menu #1046 
- [x] Settings fields adjustments
